### PR TITLE
Add abstract field

### PR DESCRIPTION
**Pull request by theotheo**
Not sure I account all thing, but at least I've check it and it works
image

### CODE REVIEW

**Review by dvanoni — APPROVED** [review]
@theotheo this is great! Thank you so much for contributing! I've pulled your PR and tested locally. Everything looks good to me!

**Comment by jigarp12892** [comment]
Hello @theotheo  and @dvanoni , another awesome addition! Is there any way I can trigger this change to existing entries in the notion database? A new paper added to the zotero collection puts the Abstract in Notion just fine, but existing ones don't change.

I even tried creating a dummy 'edit' in Zotero like adding a tag or something so that notero re-syncs, but it does not trigger the abstract being pulled in.

**Comment by dvanoni** [comment]
@jigarp12892 doing an edit like that is probably the best way to trigger the re-sync for now (until #21 gets implemented). I was able to get that to work as show in the video below.

I'm curious why it's not working for you. 🤔 Do you get any errors during the sync? Would you mind opening **Tools > Developer > Error Console** from the Zotero menu before syncing and let me know if you notice any messages there?

https://user-images.githubusercontent.com/299357/150908961-e35323d3-a405-44e1-a316-3f692f618667.mp4

**Comment by jigarp12892** [comment]
Hi @dvanoni , I tried what you suggested. No error messages. See video below

https://user-images.githubusercontent.com/34984226/150982615-df9b102e-4588-4a16-8f1b-5e7723840b73.mp4

**Comment by dvanoni** [comment]
@jigarp12892 I'm glad you were able to figure it out! I'm curious what the problem was with the abstract. Were there special characters or something that was causing the sync not to work? Or did Zotero just not have the abstract at all?

**Comment by jigarp12892** [comment]
Zotero did not pull in the abstract at all. I guess it was silly of me to assume that it always will :P. So nothing on Notero's end was the problem. I even tried pulling in an abstract with special characters in. It works perfectly !

**Comment by dvanoni** [comment]
Great! Thanks for doing that extra testing @jigarp12892!

**Comment by jigarp12892** [comment]
Happy to help @dvanoni. In fact, you can count on me if you need a minion to do more stress testing. I would love to contribute as a dev, but I'm afraid the cards might start flowing from 'completed' to 'in process' 🤣

**Comment by pmmendoza** [comment]
Hi @dvanoni short follow-up on this bc. I don't know how to reach out to you otherwise - should any changes in Notion (e.g. addition of a Tag) also be synced back to zotero?

If not is this a possible feature or is it too complex (risk of duplicating / messing up things);

**Comment by dvanoni** [comment]
@pmmendoza, that's a good question! Unfortunately, it's not possible for the plugin to be notified of any updates within Notion.

The question of syncing updates from Notion back into Zotero was also [asked by someone in the Zotero forums](https://forums.zotero.org/discussion/comment/393244/#Comment_393244). It would be neat, but it's unfortunately beyond the scope of the plugin. Getting updates from Notion into Zotero would require setting up a hosted service that subscribes to webhooks from Notion and then uses the Zotero API to update items in Zotero. Notion has yet to release official webhook support, but there are some third-party tools that can be used for this. In theory this is technically possible, but it would be a separate project from the plugin and something I wouldn't be able to take on anytime soon.

**Pull request merged**
